### ISSUE TITLE
DiskExtractor can construct with QFileDevice* or QIODevice*

### ISSUE THREAD

**Issue by kanryu** [antony-jr/QArchive#20]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
Hi,

I'm looking for a Qt library that expands the 7z archives and found yours.

I examined the DiskExtractor class, but there seems to be no way to create an instance from on-memory archive data. QFile is for reading and writing real files on disk, and virtual on-memory archives will not work. Therefore, you should instead use the more primitive interfaces commonly used with Qt, such as QFileDevice or QIODevice. This will also allow us to implement virtual files.

**Comment by antony-jr** [comment]
@kanryu For a long time nobody requested this feature So I was waiting for someone to ask. Its called DiskExtractor because it can only extract archives based on the storage of the computer. Now that you have raised an issue , I will look into it. So Thanks for reporting this.

From the docs ,
> The QArchive::DiskExtractor class helps to extract archives that are based on the disk, (i.e) The storage of the computer. This class can extract all formats supported by libarchive , this can aslo be used to read the contents of the given archive.

**Please wait for a while , I will be implementing it.**

**Comment by antony-jr** [comment]
@kanryu I've made the DiskExtractor to construct with QIODevice , please try this branch -> https://github.com/antony-jr/QArchive/tree/use-qiodevice 

The important thing is that , **you cannot extract 7zip archives from sequential QIODevice because they can't seek.** libarchive still does not fully support 7zip archives , it has a lot of errors. I ended up re-implementing archive_read_open  from scratch using QIODevice

**Comment by kanryu** [comment]
thank you for your effort. There are not a few cases where it is necessary to extract an archive that is in memory, for example if you have an archive within an archive, you will be able to extract the inner archive without saving to a file.

**Comment by antony-jr** [comment]
Anyways , I will be merging it to master after I've made some cosmetic changes. So please wait till then. Use the mentioned branch for testing and other stuff.

**Comment by antony-jr** [comment]
Now you can construct the QArchive::DiskExtractor with any class which has QIODevice as the base class , here is the [documentation](https://antony-jr.github.io/QArchive/docs/QArchiveDiskExtractor.html#diskextractorqiodevice-archive-qobject-parent-nullptr-bool-singlethreaded-true).

Thank you for reporting this.
