### ISSUE TITLE
bad performance

### ISSUE THREAD

**Issue by insar-dev** [antony-jr/QArchive#78]
**Select your issue type:** (check at least one)

- [ ] Suggestion

**Describe your issue:**

There are 282 files in archive(about 3GB).  I exact only one small file, but it takes lots of time.
I guess the following codes effect the performance.

![image](https://user-images.githubusercontent.com/1676595/207572394-02b6173b-4347-4b29-b4a3-f844eb6b96d3.png)

why always seeks to prev position?

If i use libarchive api(archive_read_open_filename & archive_read_next_header) directly, it runs fast.
but in QArchive, archive_read_next_header takes lots of time, the diff is IO operation.

**Ways to Reproduce the issue (optional):**

**Comment by insar-dev** [comment]
why not use libarchive's read?

**Comment by antony-jr** [comment]
@insar-dev Yes I'm aware of this performance issues... The check is not needed in the code (it's just old code need to refactor a lot some time soon). We don't use libarchive read because in memory mode we might want to read archive from QIODevice, that's the only reason. Nothing else. Say for example, if you download archive data directly from the internet, you can place the data directly in a QBuffer and pass it on to QArchive to extract the files. 

Wait for a while, I'm planning to use concurrency to solve the performance issue, that might take a while.

**Comment by antony-jr** [comment]
For now I think we can remove the check entirely, it's just not right.

**Comment by antony-jr** [comment]
Can you remove the if check entirely and not just store previous value at all? I think I need to try that. The check seems useless here and all it does is add extra cpu cycles. My bad.

**Comment by antony-jr** [comment]
@insar-dev can you try the master branch, see how the performance is? I've optimize the io reader to some extent, it should be faster than before.
